name: Run ADO to GitHub Sync with PowerShell

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Check out repo        
        uses: actions/checkout@v3
        
        
#       - name: Check out FromTFS
#         uses: actions/setup-powershell@v2
      - name: run powershell script 
        shell: pwsh
        env: 
           DESTINATIONPAT: ${{ secrets.DESTINATIONPAT }}
           SOURCEPAT: ${{ secrets.SOURCEPAT }}
        run: |
         chmod 777 ./SyncTFStoGitHub.ps1 
         pwsh ./SyncTFStoGitHub.ps1 -$DESTINATIONPAT -$SOURCEPAT 
