name: Run ADO to GitHub Sync with PowerShell

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo        
        uses: actions/checkout@v3
#       - name: Check out FromTFS 
        env: 
           DESTINATIONPAT: ${{ secrets.DESTINATIONPAT }}
           SOURCEPAT: ${{ secrets.SOURCEPAT }}
      - run: |
         chmod 777 ./SyncTFStoGitHub.ps1 
         ./SyncTFStoGitHub.ps1 -$DESTINATIONPAT -$SOURCEPAT 
